// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzrrdbknyjkaenawzlgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6cnJkYmtueWprYWVuYXd6bGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MjI2ODAsImV4cCI6MjA2MzI5ODY4MH0.jwO1-ivoMUUIfDLKZB1imXMthRF_e82mVjnvndDLV1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);